use_frameworks!

platform :ios, '8.0'

target 'XALFrameworksDebug_Example' do
  pod 'XALFrameworksDebug', :path => '../'

  target 'XALFrameworksDebug_Tests' do
    inherit! :search_paths

    
  end
end
